export const rotatingPhrases = [
  'Man and van London to Manchester for just £65',
  'Full home removal Manchester to Glasgow from £180',
  'Student move Leeds to Birmingham only £70',
  'Same-day delivery Bristol to London from £50',
  'Affordable man with a van Liverpool to Leeds £60',
  'Office relocation London to Birmingham £220',
  'Single item move Manchester to Sheffield £45',
  'Flat removal Edinburgh to Glasgow £85',
  'House move London to Oxford £150',
  'Furniture delivery Nottingham to Leicester £55',
  'Student special Cardiff to Bristol only £50',
  'Man and van Birmingham to Liverpool £75',
  'Express service London to Cambridge £65',
  'Long-distance move Manchester to London £200',
  'Full packing + removal Leeds to Newcastle £240',
  'Budget van hire London to Brighton £70',
  'Quick sofa delivery Liverpool to Manchester £40',
  'Flat move Oxford to London £120',
  'Affordable van service Glasgow to Edinburgh £60',
  'Man and van London to Southampton £95',
  'Full removal Nottingham to Sheffield £130',
  'Student relocation Manchester to Leeds £55',
  'Office move Birmingham to Cardiff £190',
  'Single chair delivery London to Birmingham £35',
  'House removal Bristol to Manchester £175',
  'Express man with van London to Reading £65',
  'Student deal Leicester to Nottingham £45',
  'Man and van Sheffield to Leeds £55',
  'Flat removal Glasgow to Aberdeen £160',
  'Budget move London to Liverpool £140',
  'Furniture pickup Birmingham to Manchester £50',
  'House clearance London to Brighton £150',
  'Man and van Cardiff to London £110',
  'Quick student move Newcastle to Leeds £60',
  'Affordable move Liverpool to Sheffield £65',
  'Same-day service London to Bristol £90',
  'Man with van Edinburgh to Dundee £75',
  'Office relocation London to Leeds £210',
  'Full house move Manchester to York £170',
  'Student relocation Cambridge to London £80',
  'Man and van London to Milton Keynes £70',
  'Flat move Sheffield to Nottingham £60',
  'House move Birmingham to Leicester £95',
  'Furniture delivery Cardiff to Manchester £85',
  'Quick sofa move London to Oxford £55',
  'Express relocation Liverpool to Glasgow £150',
  'Man with van Brighton to London £80',
  'Affordable move Bristol to Birmingham £75',
  'Flat clearance Leeds to Manchester £65',
  'House removal Oxford to Cambridge £120',
  'Student offer Nottingham to Sheffield £45',
  'Van service London to Newcastle £220',
  'Budget man and van Glasgow to London £230',
  'Furniture delivery Edinburgh to London £240',
  'Express home removal Birmingham to Bristol £160',
  'Same-day sofa move London to Cardiff £95',
  'Full relocation Liverpool to Edinburgh £250',
  'Student move Southampton to London £70',
  'Quick man with van Leeds to Birmingham £60',
];
