name: SEO Integrity
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-seo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      # Install pnpm explicitly so it's always on PATH
      - name: Install pnpm
        run: npm install -g pnpm@10.13.1

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies (frozen, workspace root)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile --prefer-offline
          else
            echo "WARN: pnpm-lock.yaml missing, falling back (non-deterministic)"
            pnpm install --no-frozen-lockfile --prefer-offline
          fi

      # If you're on pnpm v10, approve postinstall scripts explicitly
      - name: Approve build scripts (pnpm v10)
        run: pnpm approve-builds @prisma/client @prisma/engines @sentry/cli core-js esbuild prisma unrs-resolver

      - name: Rebuild (run approved postinstalls)
        run: pnpm rebuild -r

      - name: Build Next.js (with NextAuth env vars)
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: https://speedy-van.onrender.com
          NODE_ENV: production
        run: |
          echo "Building Next.js app with NextAuth configuration..."
          pnpm --filter ./apps/web build
          echo "Build completed successfully"

      - name: Run SEO checks
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: https://speedy-van.onrender.com
          NODE_ENV: production
        run: |
          echo "Running SEO checks..."
          echo "Checking Next.js build integrity..."
          pnpm --filter ./apps/web run seo-check
          echo "✅ SEO checks completed successfully"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


